# site settings

title: Mayanna Oliveira
description: In id excepteur consequat aliqua tempor.
taglong: In id excepteur consequat aliqua tempor
tagshort: Mayanna Oliveira
url: https://google.com/
baseurl: ""
permalink: pretty
repo: https://github.com/mayannaoliveira/mayannaoliveira.github.io

# author settings

author:
  name: Mayanna Oliveira
  email: mayannasoliveira@gmail.com
photo: /assets/jpg/github.png

# social media links

social:
  facebook: mayannaoliveira
  github: mayannaoliveira
  instagram: mayannaoliveira
  linkedin: mayannaoliveira
  stackoverflow: 16884312/mayanna
  twitter: oliveiramayanna

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
